openapi: 3.0.2
info:
    title: Meter API
    version: 1.0.0
    description: Parking Meter API. Allows meters to provide their updates via HTTP POST.
paths:
    /meter/status:
        post:
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/meterstatus'
                required: true
            responses:
                '200':
                    content:
                        application/json: {}
                    description: update status
            operationId: create
            summary: update meter status
            description: update meter status
components:
    schemas:
        meterstatus:
            title: Root Type for meterstatus
            description: ''
            type: object
            properties:
                key:
                    description: Key of meter update
                    type: string
                value:
                    description: Meter status
                    type: object
                    properties:
                        meterId:
                            type: string
                        timestamp:
                            format: int32
                            type: integer
                        status:
                            type: string
            example:
                key: F6PeB2XQRYG-8EN5yFcrP
                value:
                    meterId: F6PeB2XQRYG-8EN5yFcrP
                    timestamp: 1510934784
                    status: unknown
