---
- name: Evaluate {{ registration_namespace }} namespace if not exists 
  k8s:
    api_version: v1
    kind: Namespace
    name: '{{ registration_namespace }}'
    state: present

- debug: 
    var: '{{num_supported_users|int}}'

- name: Evaluate app instance
  k8s:
    state: present
    namespace: '{{ registration_namespace }}'
    resource_definition: "{{ lookup('template', 'registration-app.yaml.j2') }}"
