---
- name: Process user namespace
  k8s:
    api_version: v1
    kind: Namespace
    name: '{{__user}}'
    state: present
  register: _user_namespace
  retries: 30
  delay: 5
  until:
   - _user_namespace is succeeded

# - name: Process user che namespace
#   k8s:
#     api_version: v1
#     kind: Namespace
#     name: '{{__user}}-che'
#     state: present

# - name: Create Role to access Terminal
#   k8s:
#     state: present
#     resource_definition: "{{ lookup('template', 'pod-exec-role.yaml.j2') }}"  
#   when: __user == "user1"

- name: Give {{__user}} access to projects
  k8s:
    state: present
    resource_definition: "{{ lookup('template', 'user-rolebinding.yaml.j2') }}"
  loop:
    - { user: '{{__user}}', namespace: '{{__user}}', role: 'admin' }
    # - { user: '{{__user}}', namespace: '{{__user}}-che', role: 'admin' }
    # - { user: '{{__user}}', namespace: '{{ shared_namespace }}', role: 'view' }
    # - { user: '{{__user}}', namespace: '{{ shared_namespace }}', role: 'pod-exec' }
  loop_control:
    loop_var: item_project

# - name: Create project infraestructure for {{__user}}
#   k8s:
#     state: present
#     namespace: '{{__user}}'
#     resource_definition: "{{ lookup('template', 'user_project.yaml.j2') }}"

- name: Create terminal for {{__user}}
  block:
  - name: Log in OCP as {{__user}}
    k8s_auth:
      host: "{{api_url}}"
      verify_ssl: no
      username: '{{__user}}'
      password: '{{ocp4_workload_dil_serverless_workshop_openshift_user_password}}'
    register: k8s_auth_results
  - name: Create DevWorkspace for {{__user}}
    k8s:
      host: "{{api_url}}"
      verify_ssl: no
      api_key: '{{ k8s_auth_results.k8s_auth.api_key }}'
      state: present
      resource_definition: "{{ lookup('template', 'terminal-devworkspace.yaml.j2') }}"
