---
- name: Evaluate openshift-serverless namespace if not exists 
  k8s:
    api_version: v1
    kind: Namespace
    name: openshift-serverless
    state: present

- name: Evaluate Operator Group
  k8s:
    api_version: operators.coreos.com/v1alpha2
    kind: OperatorGroup
    name: openshift-serverless
    namespace:  openshift-serverless

- name: Evaluate Serverless Subscription
  k8s:
    state: present
    resource_definition: "{{ lookup('template', 'serverless-subscription.yaml.j2') }}"

- name: Wait for Serverless operator to install
  k8s_info:
    api_version: apiextensions.k8s.io/v1beta1
    kind: CustomResourceDefinition
    name: knativeservings.operator.knative.dev
  register: crd_knativeservings
  until: crd_knativeservings.resources | list | length == 1
  retries: 10
  delay: 30

- name: Evaluate knative-serving namespace if not exists 
  k8s:
    api_version: v1
    kind: Namespace
    name: knative-serving
    state: present

- name: Evaluate Serverless Subscription
  k8s:
    state: present
    resource_definition: "{{ lookup('template', 'serverless_knative_serving.yaml.j2') }}"

- name: Evaluate knative-eventing namespace if not exists 
  k8s:
    api_version: v1
    kind: Namespace
    name: knative-eventing
    state: present

- name: Evaluate Serverless Subscription
  k8s:
    state: present
    resource_definition: "{{ lookup('template', 'serverless_knative_eventing.yaml.j2') }}"