---
- name: Log in OCP as {{__user}}
  k8s_auth:
    host: "{{api_url}}"
    verify_ssl: no
    username: '{{__user}}'
    password: '{{ocp4_workload_dil_serverless_workshop_openshift_user_password}}'
  register: k8s_auth_results
- name: Create DevWorkspace for {{__user}}
  k8s:
    host: "{{api_url}}"
    verify_ssl: no
    api_key: '{{ k8s_auth_results.k8s_auth.api_key }}'
    state: present
    resource_definition: "{{ lookup('template', 'terminal-devworkspace.yaml.j2') }}"