apiVersion: kafka.strimzi.io/v1alpha1
kind: KafkaMirrorMaker2
metadata:
  name: smartcity
spec:
  clusters:
  - alias: "edge"
    bootstrapServers: edge-kafka-bootstrap.{{user}}-smartcity-edge.svc:9092
  - alias: "smartcity-central"
    bootstrapServers: {{smartcity-central-bootstrap-server}}
    authentication:
      type: plain
      username: {{smartcity-central-service-account-id}}
      passwordSecret:
        secretName: rh-cloud-services-service-account
        password: client-secret
    tls:
      trustedCertificates: []
    config:
      config.storage.replication.factor: 1
      offset.storage.replication.factor: 1
      status.storage.replication.factor: 1
